name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        go: [1.14.x, 1.15.x, 1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
          go-version: ${{ matrix.go }}
    - run: go test -race ./...
