name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        go: [1.22.x, 1.23.x, 1.24.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
          go-version: ${{ matrix.go }}
    - run: go test -race ./...
